// parlay CLI usage and per-command help text.

import { SERVER } from "./config"

export const USAGE = `parlay — talk to a Parlay chat server (current target: ${SERVER})

Usage:
  parlay                          Live status: subscribers, agents, last 3 messages
  parlay status                   Same as bare parlay
  parlay subscribers [--full]     Connection counts (--full: raw JSON)
  parlay agents [--full]          List registered agents (--full: raw JSON)
  parlay nickname <nick...>       Set voice nicknames for THIS agent (picker/voice channel-switch)
  parlay nickname --agent <id> <nick...>   Set nicknames for a named agent (--clear to remove)
  parlay send                     List agents you can message
  parlay send --<agent-id> <text> Send attributed message to that agent's channel
  parlay say <text...>            Reply to YOUR OWN channel (spawned agents; identity from PARLAY_AGENT_ID)
  parlay reply <text...>          Alias for 'say' (bare 'reply' wraps this)
  parlay scratchpad [<note>]      Your durable task notes; no args = read (bare 'scratchpad' wraps this)
  parlay identity [<fact>]        Your durable self-knowledge; no args = read (bare 'identity' wraps this)
  parlay alert <text...>          Broadcast an alert to all pollers + agents (immediate)
  parlay alert --stagger <text...>      Spread delivery over time (avoid a fleet-wide API spike)
  parlay alert --agent <id> <text...>   Alert one agent channel
  parlay history [N] [--full]     Last N messages, truncated (default 20; --full: untruncated)
  parlay monitor --agent <id>     Relay-backed enroll + stream — emits CHAT_MSG lines (for Monitor{})
  parlay monitor --legacy-poll [--agent <id>]   Old independent poll loop (no relay)
  parlay stats                    Message memory/complexity stats (count, sizes, ages, images)
  parlay health                   Server vitals: relay, memory, pulse wrapper, eval-engine
  parlay doctor                   THIS agent's self-diagnosis: PASS/WARN/FAIL + fix per check
  parlay context-check <pct>      Rotation advisory: OK, or ROTATE (exit 3) at/above the threshold (default 85%)
  parlay robots-watch [--once]    Event poll-daemon: robots-created→mechanic-dispatch, request-closed→notify
  parlay launch                   List all known agents + live status (from ~/.parlay/agents/)
  parlay launch <id>              Spawn an offline agent via parlay-spawn (uses identity frontmatter)
  parlay variant launch <id>      Fork a live agent into an isolated git-worktree variant
  parlay variant list [<id>]      List variants (optionally filtered to one primary)
  parlay variant merge <id>       Merge variant's insights back into primary (idempotent)
  parlay variant teardown <id>    Merge + remove worktree + unregister variant
  parlay lavish-import            Import lavish sessions
  parlay help                     Show this help

Any subcommand accepts --help. Exit codes: 0 ok, 1 server/runtime error, 2 usage error.

Env:
  PARLAY_SERVER   Server base URL (coded default http://localhost:4242; this fleet sets it to the Pulse server)
`

const HELP: Record<string, string> = {
  status: `parlay status — live snapshot: subscriber counts, agent list, last 3 messages.\nUsage: parlay [status]`,
  subscribers: `parlay subscribers — connection counts (panel clients, pollers, registered agents).\nUsage: parlay subscribers [--full]\n  --full   Print the raw JSON from /api/chat/subscribers`,
  agents: `parlay agents — registered agents, one per line (id, name, color).\nUsage: parlay agents [--full]\n  --full   Print the raw JSON from /api/chat/agents`,
  nickname: `parlay nickname — assign voice nicknames so the channel picker + voice channel-switch resolve an agent by an easy spoken word.\nUsage: parlay nickname <nick> [<nick2> …]        set nicknames for THIS agent (PARLAY_AGENT_ID)\n       parlay nickname --agent <id> <nick> …     set nicknames for a named agent\n       parlay nickname --agent <id> --clear      remove all nicknames\nThe FIRST nickname becomes the picker's display label for that channel. Metadata-only\nupsert via /api/chat/register-agent — does not post a message. Re-running replaces the set.`,
  send: `parlay send — list or message another agent's channel (all messages visible to the human).\nUsage: parlay send                          → list agents you can message\n       parlay send --<agent-id> "text"     → send attributed message to that agent's channel\nExamples:\n  send                      # prints: send --mayor, send --shepherd, …\n  send --mayor "heads up"   # lands on mayor's channel; human sees it too\n  send --shepherd "done"    # attributed to PARLAY_AGENT_ID (auto-filled)\n  --from <id>               # override sender attribution (rarely needed)\nAll messages land on the target's SHARED human channel — no private side channels.\nThe receiving agent's monitor emits: CHAT_MSG|id|role|text|from:<sender>`,
  say: `parlay say — reply to your OWN Parlay channel with no boilerplate (for agents spawned by parlay-spawn).\nUsage: parlay say <text...>   |   echo "long reply" | parlay say\n  Identity comes from PARLAY_AGENT_ID (set at spawn); override with --agent <id>.\n  The server keeps your registered name/color, so you only supply the text.\n  Alias: parlay reply. Dead-simple wrapper on PATH: reply "<text>".\n  Shutdown guard: if you post while an OPEN handoff is not yet submitted, a loud stderr\n  warning steers you to 'identity --submit' — chat here is the create→submit death window.\n  The send still goes through; the warning never blocks it.`,
  scratchpad: `parlay scratchpad — your durable task notes, keyed by PARLAY_AGENT_ID (survives restarts).\nUsage: scratchpad '<note>'   append   |   scratchpad   read   |   scratchpad --clear | --path\n  Also: --agent <id>, and stdin (echo 'note' | scratchpad). Store: ~/.parlay/agents/<id>/scratchpad.md`,
  identity: `parlay identity — your durable self-knowledge (traits, failure modes, lessons), keyed by PARLAY_AGENT_ID.\nUsage: identity '<fact>'   add   |   identity   read   |   identity --clear | --path\n  identity --handoff [<handoff-id>]         pin a pointer to your handoff bead (pin only — does not restart).\n  identity --dismiss-handoff [<handoff-id>] NON-DESTRUCTIVE dismiss of an inherited stale handoff. Pins the pointer\n                                             (same as --handoff) but prints a "dismissed, context NOT reset" message.\n                                             Use when a fresh context reusing an agent-id sees a prior session's stale\n                                             open handoff and gets nagged. Does NOT trigger a context reset.\n  identity --submit [<handoff-id>]          PERSISTENT agent: pin it AND reset your context — ENDS the session and relaunches you with a\n                                     fresh context that recovers via identity -> handoff -> scratchpad. Add --dry to preview.\n  The handoff id is OPTIONAL: omit it and your NEWEST OPEN handoff is resolved from the store (agent-scoped), so\n                                     'handoff create … && identity --submit' is ONE atomic act — no room for an interposed\n                                     step to strand your shutdown, and a bare submit recovers a create that already landed.\n  ATOMIC CONTRACT: create then submit with NOTHING between. Post no chat in that window — 'parlay say'/'reply' will\n                                     warn you if you do. The pin is set at CREATE time, so recovery survives a missed submit.\n  identity --complete <store-item>  SINGLE-USE agent: close the work item you finished (e.g. task-abc → 'task close') and\n                                     END for good — no restart. The counterpart to --submit. Add --dry to preview.\n  Both are the whole shutdown — no separate sudoku/context-reset step.\n  identity --rename <old-id> --to <new-id> [--name N] [--color C] [--cwd P] [--model M] [--preserve]\n                                     Move an agent's store to a new id and re-register with the server. Guards against\n                                     clobbering an existing <new-id>. --preserve drops the ephemeral marker (adopt an\n                                     ephemeral into a durable identity). Does NOT relaunch — relaunch with 'identity --launch <new-id>'.\n  identity --reap-ephemeral [--older-than <hours>h] [--dry]\n                                     GC ephemeral (hash-identity) agents whose identity.md is idle past the window\n                                     (default 24h). --dry previews without deleting.\n  Also: --agent <id>, and stdin. Read identity on every startup to recover yourself. Store: ~/.parlay/agents/<id>/identity.md`,
  alert: `parlay alert — alert pollers + agents. Immediate broadcast by default; auto-staggers above a fleet threshold, or force it with --stagger, to avoid a fleet-wide API spike (task-j870).\nUsage: parlay alert [--agent <id>] [--stagger | --no-stagger] [--interval <sec>] [--batch <n>] <text...>\n  --agent <id>      Deliver only to one agent channel (immediate; nothing to stagger)\n  --stagger         Force spread delivery across agents over time\n  --no-stagger      Force an immediate broadcast even above the auto-stagger threshold\n  --interval <sec>  Seconds between staggered batches (default 1.5, ±25% jitter)\n  --batch <n>       Agents delivered per batch (default 1)\nAuto-stagger: a bare 'parlay alert' broadcasts immediately for a small fleet, but auto-staggers when the\nlive fleet exceeds the threshold — so a routine broadcast can't thunder the herd. Env overrides:\n  PARLAY_ALERT_STAGGER_THRESHOLD (default 8), PARLAY_ALERT_STAGGER_INTERVAL (1.5), PARLAY_ALERT_STAGGER_BATCH (1).`,
  history: `parlay history — print recent messages (server-bounded).\nUsage: parlay history [N] [--full]\n  N        How many messages (default 20)\n  --full   Untruncated text plus id and channel per message`,
  monitor: `parlay monitor — enroll with the relay and stream CHAT_MSG|id|role|text lines on stdout.\nUsage: parlay monitor --agent <id> [--legacy-poll]\n  --agent <id>    Agent channel to enroll + stream (required unless --legacy-poll)\n  --legacy-poll   Use the old independent poll loop with no relay (global feed if no --agent)\n\nDefault path registers <id> with the central relay (tools/relay/parlay-relay must\nbe running) and execs 'tail -F' on the agent's spool — ~1.2MB per agent, one relay\nfans out to all. See tools/RELAY_MONITOR.md.`,
  stats: `parlay stats — message memory and complexity snapshot from the server.\nFetches up to 2000 messages and reports: count, total estimated size, avg/largest message, user vs agent split, image attachments, action cards, oldest/newest timestamps.\nPair with Ctrl+Shift+D in the panel for bundle load timing and live memory breakdown.`,
  health: `parlay health — the SERVER's vitals in one glance.\nChecks: relay reachable (subscribers/pollers/agents counts + memory/history stats), the Pulse wrapper's\n/api/pulse/health when the relay runs inside Pulse, and the eval-engine /health (protocol version).\nExit 1 if the relay or engine is down. Same view for every caller — for YOUR OWN state, run: parlay doctor`,
  doctor: `parlay doctor — THIS agent's self-diagnosis; every check prints PASS/WARN/FAIL plus the fix command.\nChecks: PARLAY_AGENT_ID set → server reachable → registered on the relay → monitor listening (presence) →\nidentity.md/scratchpad.md exist, identity frontmatter parses and matches the agent id (handoff pointer noted) →\neval-engine reachable. Runs every check even after failures. Exit 1 if anything FAILed.\nEnv: PARLAY_SERVER, PARLAY_AGENT_ID, PARLAY_AGENT_HOME, PARLAY_EVAL_ENGINE_URL.`,
  launch: `parlay launch — discover and launch agents defined in ~/.parlay/agents/.\nUsage: parlay launch          → list all known agents with live status\n       parlay launch <id>    → spawn the named agent via parlay-spawn (reads identity.md for name/color/cwd/model)\nOffline agents are clearly marked; spawning fires the standard identity→handoff→scratchpad recovery chain.`,
  variant: `parlay variant — manage variant agents (isolated git-worktree forks of an existing agent).\nSubcommands:\n  launch <primary-id> [--label <suffix>] [--model MODEL]\n      Fork a primary into a new variant. Creates a git worktree at ~/.parlay/worktrees/<variant-id>.\n      Label defaults to wt1, wt2, … (auto-incremented). Variant id: <primary>-<label>.\n  list [<primary-id>]\n      List all variants, optionally filtered to a specific primary.\n  merge <variant-id>\n      Append novel identity facts + scratchpad notes from the variant into the primary.\n      Deduplicated by content; merged lines tagged [from: <variant-id>]. Idempotent.\n  teardown <variant-id> [--force]\n      Merge insights (unless --force), remove the git worktree, unregister from Parlay,\n      and delete the variant home. Refuses if unmerged insights exist unless --force.`,
  "lavish-import": `parlay lavish-import — import lavish sessions via the bundled importer.\nUsage: parlay lavish-import`,
  "context-check": `parlay context-check — machine-readable rotation advisory for persistent agents.\nUsage: parlay context-check <pct> [--threshold <pct>]\n  <pct>              your current context usage (0–100). Accepts 85, 85%, or 0.85. YOU pass what\n                     your harness knows — Claude Code exposes no context gauge to a CLI.\n  --threshold <pct>  rotate at/above this (default 85).\nOutput + exit codes (scriptable): below → 'OK <pct>% (threshold <t>%)', exit 0;\n  at/above → 'ROTATE: create handoff now, then identity --submit …', exit 3; bad pct → exit 2.\nRotation loop: on ROTATE, write a handoff then 'identity --submit' (atomic — see identity --help).\n  The supervisor-respawn side lives in GasCity. Example:\n    parlay context-check 87 || { handoff create … && identity --submit; }`,
  "robots-watch": `parlay robots-watch — MVP event poll-daemon (decision-4zr interim bridge).\nPolls each watched store's '<store> list --all --json', diffs a persisted per-bead status cursor, and routes each\n(store, status-change) through a handler table. Stands in for the not-yet-built beads EMIT hook (task-n1ao);\nswap the poll source for the ingest endpoint later and the router/handlers are unchanged.\nUsage: parlay robots-watch [--interval <sec>] [--once] [--verbose]\n  --interval <sec>  poll cadence (default 15; ignored with --once)\n  --once            single poll pass then exit (tests / cron)\n  --verbose         log every pass + routed event to stderr\nHandlers:\n  (a) robots bead CREATED          → mechanic-dispatch <id> (idempotent)\n  (b) request/question/task CLOSED → notify the requester channel from the bead's 'notify:<channel>' label\n                                      via 'parlay send --<channel>'\nState: $PARLAY_STATE_HOME/robots-watch/cursor.json (default ~/.parlay/…). First sighting of a store SEEDS its\ncursor and fires nothing; only transitions observed AFTER seeding fire handlers. Run under launchd for the daemon.`,
}

export function helpWanted(cmd: string, args: string[]): boolean {
  if (!args.includes("--help") && !args.includes("-h")) return false
  console.log(HELP[cmd] ?? USAGE)
  return true
}
